language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

branches:
  only:
    - master


install:
  - composer install --dev

script:
  - vendor/bin/phpcs -p --standard=PSR12 src
  - vendor/bin/phpunit
